[2025-06-23 23:32:21,711] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-23 23:32:21,711] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-23 23:32:21,711] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-23 23:32:21,711] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-23 23:32:21,755] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-23 23:33:10,527] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-23 23:33:10,527] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-23 23:33:10,542] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-23 23:33:10,542] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-23 23:33:11,976] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-23 23:33:11,976] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-23 23:33:11,976] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-23 23:33:11,976] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-23 23:33:12,030] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-23 23:34:25,225] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\accounting\forms.py changed, reloading.
[2025-06-23 23:34:27,648] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-23 23:34:27,648] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-23 23:34:27,649] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-23 23:34:27,649] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-23 23:34:27,697] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-23 23:36:18,102] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\accounting\forms.py changed, reloading.
[2025-06-24 22:10:39,789] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:10:39,790] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:10:39,790] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:10:39,790] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:10:56,104] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:10:56,104] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:10:56,104] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:10:56,104] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:17:15,736] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:17:15,736] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:17:15,736] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:17:15,736] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:17:55,704] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:17:55,720] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:17:55,720] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:17:55,720] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:18:25,512] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:18:25,512] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:18:25,512] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:18:25,512] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:18:26,751] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:18:26,751] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:18:26,751] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:18:26,751] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:18:26,796] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-24 22:18:35,792] ERROR django.request: Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\allauth\socialaccount\templatetags\socialaccount.py", line 21, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 213, in get_provider
    app = self.get_app(request, provider=provider, client_id=client_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 303, in get_app
    raise SocialApp.DoesNotExist()
allauth.socialaccount.models.SocialApp.DoesNotExist
[2025-06-24 22:18:36,094] WARNING django.request: Not Found: /favicon.ico
[2025-06-24 22:22:17,520] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:22:17,520] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:22:17,520] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:22:17,520] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:36:36,440] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:36:36,440] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:36:36,440] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:36:36,440] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:40:50,380] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:40:50,380] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:40:50,380] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:40:50,380] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:40:53,536] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:40:53,536] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:40:53,536] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:40:53,536] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:42:23,049] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:42:23,049] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:42:23,049] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:42:23,049] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:42:24,432] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:42:24,433] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:42:24,433] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:42:24,433] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:42:24,468] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-24 22:42:55,616] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:42:55,616] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:42:55,616] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:42:55,616] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:43:10,617] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:43:10,617] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:43:10,617] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:43:10,617] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:43:12,052] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:43:12,052] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:43:12,052] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:43:12,052] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:43:12,102] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-24 22:43:25,984] ERROR django.request: Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\template\library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\allauth\socialaccount\templatetags\socialaccount.py", line 21, in provider_login_url
    provider = adapter.get_provider(request, provider)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 213, in get_provider
    app = self.get_app(request, provider=provider, client_id=client_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\allauth\socialaccount\adapter.py", line 303, in get_app
    raise SocialApp.DoesNotExist()
allauth.socialaccount.models.SocialApp.DoesNotExist
[2025-06-24 22:57:43,585] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:57:43,585] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:57:43,585] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:57:43,585] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:57:55,268] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:57:55,268] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:57:55,268] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:57:55,268] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 22:58:19,962] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 22:58:19,962] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 22:58:19,962] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 22:58:19,962] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:01:03,767] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:01:03,767] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:01:03,767] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:01:03,767] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:01:31,017] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:01:31,017] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:01:31,017] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:01:31,017] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:09:08,435] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:09:08,435] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:09:08,435] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:09:08,451] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:09:13,482] INFO accounting.models: Saving FiscalYear: 
[2025-06-24 23:10:22,545] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:10:22,545] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:10:22,545] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:10:22,545] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:33:19,693] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:33:19,693] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:33:19,693] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:33:19,693] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:36:11,447] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:36:11,447] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:36:11,447] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:36:11,447] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:36:23,229] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:36:23,243] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:36:23,244] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:36:23,245] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:37:16,265] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:37:16,265] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:37:16,265] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:37:16,265] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:39:57,569] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:39:57,569] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:39:57,569] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:39:57,569] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:46:07,434] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:46:07,434] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:46:07,434] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:46:07,434] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:47:36,042] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:47:36,043] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:47:36,044] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:47:36,044] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:50:07,160] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:50:07,160] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:50:07,160] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:50:07,160] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:52:13,851] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:52:13,851] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:52:13,851] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:52:13,851] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:54:41,922] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:54:41,922] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:54:41,922] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:54:41,922] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:55:19,204] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:55:19,205] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:55:19,205] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:55:19,205] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:55:20,618] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:55:20,618] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:55:20,618] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:55:20,618] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:55:20,655] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-24 23:57:36,741] ERROR django.request: Internal Server Error: /accounting/fiscal_year/list/
Traceback (most recent call last):
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedFunction: operator does not exist: boolean = integer
LINE 9:                     AND ur.is_active = 1
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\accounting\views_list.py", line 40, in get_context_data
    context['can_add'] = PermissionUtils.has_permission(user, org, 'accounting', 'fiscalyear', 'add')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\usermanagement\utils.py", line 59, in has_permission
    permissions = PermissionUtils.get_user_permissions(user, organization)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\usermanagement\utils.py", line 36, in get_user_permissions
    cursor.execute("""
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: operator does not exist: boolean = integer
LINE 9:                     AND ur.is_active = 1
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[2025-06-24 23:58:05,192] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-24 23:58:06,814] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:58:06,814] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:58:06,814] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:58:06,814] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:58:06,860] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-24 23:58:18,924] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-24 23:58:20,335] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:58:20,335] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:58:20,335] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:58:20,350] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-24 23:58:20,375] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-24 23:58:40,762] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-24 23:58:40,762] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-24 23:58:40,762] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-24 23:58:40,762] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 00:01:15,853] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 00:01:15,853] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 00:01:15,853] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 00:01:15,853] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 00:01:17,141] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 00:01:17,141] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 00:01:17,141] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 00:01:17,141] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 00:01:17,181] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 00:02:39,027] ERROR django.request: Internal Server Error: /accounting/fiscal_year/list/
Traceback (most recent call last):
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedFunction: operator does not exist: boolean = integer
LINE 9:                     AND ur.is_active = 1
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\accounting\views_list.py", line 40, in get_context_data
    context['can_add'] = PermissionUtils.has_permission(user, org, 'accounting', 'fiscalyear', 'add')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\usermanagement\utils.py", line 59, in has_permission
    permissions = PermissionUtils.get_user_permissions(user, organization)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\usermanagement\utils.py", line 36, in get_user_permissions
    cursor.execute("""
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: operator does not exist: boolean = integer
LINE 9:                     AND ur.is_active = 1
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[2025-06-25 00:02:43,930] ERROR django.request: Internal Server Error: /accounting/fiscal_year/list/
Traceback (most recent call last):
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedFunction: operator does not exist: boolean = integer
LINE 9:                     AND ur.is_active = 1
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\accounting\views_list.py", line 40, in get_context_data
    context['can_add'] = PermissionUtils.has_permission(user, org, 'accounting', 'fiscalyear', 'add')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\usermanagement\utils.py", line 59, in has_permission
    permissions = PermissionUtils.get_user_permissions(user, organization)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\usermanagement\utils.py", line 36, in get_user_permissions
    cursor.execute("""
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: operator does not exist: boolean = integer
LINE 9:                     AND ur.is_active = 1
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[2025-06-25 21:54:24,936] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 21:54:24,936] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 21:54:24,936] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 21:54:24,936] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 21:54:26,284] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 21:54:26,284] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 21:54:26,284] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 21:54:26,284] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 21:54:26,319] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:02:40,281] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\accounting\views_list.py changed, reloading.
[2025-06-25 22:02:42,485] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:02:42,485] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:02:42,485] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:02:42,485] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:02:42,561] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:03:15,323] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-06-25 22:03:33,656] WARNING django.request: Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-06-25 22:04:04,041] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\accounting\views_list.py changed, reloading.
[2025-06-25 22:04:05,874] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:04:05,874] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:04:05,889] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:04:05,890] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:04:05,958] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:04:10,007] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\accounting\views_list.py changed, reloading.
[2025-06-25 22:04:11,657] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:04:11,657] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:04:11,672] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:04:11,672] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:04:11,703] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:05:09,628] WARNING django.request: Not Found: /favicon.ico
[2025-06-25 22:11:30,416] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:11:32,599] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:11:32,599] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:11:32,599] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:11:32,600] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:11:32,633] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:12:22,892] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:12:24,724] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:12:24,724] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:12:24,724] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:12:24,740] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:12:24,768] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:12:35,095] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:12:35,095] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:12:35,095] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:12:35,095] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:14:33,683] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:14:35,910] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:14:35,911] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:14:35,911] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:14:35,911] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:14:35,949] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:14:45,150] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:14:47,197] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:14:47,198] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:14:47,198] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:14:47,198] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:14:47,248] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:15:13,334] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:15:14,971] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:15:14,980] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:15:14,981] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:15:14,981] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:15:15,040] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:15:19,002] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:15:20,560] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:15:20,560] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:15:20,560] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:15:20,560] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:15:20,603] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:16:16,511] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:16:16,512] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:16:16,512] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:16:16,512] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:16:39,583] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:16:41,137] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:16:41,137] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:16:41,137] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:16:41,138] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:16:41,162] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:17:33,679] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:17:35,923] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:17:35,923] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:17:35,924] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:17:35,924] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:17:35,975] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:18:21,593] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:18:21,593] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:18:21,593] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:18:21,593] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:18:56,703] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:18:58,644] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:18:58,645] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:18:58,646] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:18:58,647] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:18:58,688] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:19:16,389] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:19:18,383] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:19:18,383] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:19:18,383] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:19:18,383] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:19:18,440] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:19:36,558] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:19:38,817] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:19:38,817] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:19:38,818] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:19:38,818] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:19:38,864] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:19:43,513] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:19:45,574] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:19:45,574] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:19:45,574] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:19:45,575] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:19:45,613] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:19:49,417] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:19:49,417] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:19:49,417] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:19:49,417] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:20:12,094] ERROR django.request: Internal Server Error: /accounting/fiscal_year/list/
Traceback (most recent call last):
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedFunction: operator does not exist: boolean = integer
LINE 9:                     AND ur.is_active = 1
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\accounting\views_list.py", line 40, in get_context_data
    context['can_add'] = PermissionUtils.has_permission(user, org, 'accounting', 'fiscalyear', 'add')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\usermanagement\utils.py", line 59, in has_permission
    permissions = PermissionUtils.get_user_permissions(user, organization)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\usermanagement\utils.py", line 36, in get_user_permissions
    cursor.execute("""
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: operator does not exist: boolean = integer
LINE 9:                     AND ur.is_active = 1
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[2025-06-25 22:21:10,278] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:21:12,535] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:21:12,535] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:21:12,536] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:21:12,536] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:21:12,578] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:21:22,754] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:21:24,358] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:21:24,359] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:21:24,359] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:21:24,360] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:21:24,394] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:21:54,238] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:21:56,119] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:21:56,130] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:21:56,130] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:21:56,131] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:21:56,181] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:22:10,864] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:22:13,015] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:22:13,015] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:22:13,015] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:22:13,015] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:22:13,065] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:22:20,182] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:22:20,182] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:22:20,182] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:22:20,182] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:24:41,132] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:24:42,865] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:24:42,865] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:24:42,865] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:24:42,865] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:24:42,911] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:26:43,735] INFO django.utils.autoreload: C:\PythonProjects\ERPCURSOR\Himalytix\ERP\scripts\create_default_data.py changed, reloading.
[2025-06-25 22:26:45,271] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:26:45,272] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:26:45,272] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:26:45,277] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:26:45,309] INFO django.utils.autoreload: Watching for file changes with StatReloader
[2025-06-25 22:26:47,304] WARNING metadata.watcher: watchdog package not available. File watching will be disabled. Error: No module named 'watchdog'
[2025-06-25 22:26:47,305] WARNING metadata.watcher: MetadataWatcher initialized without watchdog support
[2025-06-25 22:26:47,305] WARNING metadata.watcher: Cannot start watcher: watchdog not available
[2025-06-25 22:26:47,306] INFO metadata.apps: Metadata watcher started in development mode
[2025-06-25 22:27:10,992] ERROR django.request: Internal Server Error: /accounting/fiscal_year/list/
Traceback (most recent call last):
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedFunction: operator does not exist: boolean = integer
LINE 9:                     AND ur.is_active = 1
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\accounting\views_list.py", line 40, in get_context_data
    context['can_add'] = PermissionUtils.has_permission(user, org, 'accounting', 'fiscalyear', 'add')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\usermanagement\utils.py", line 59, in has_permission
    permissions = PermissionUtils.get_user_permissions(user, organization)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\usermanagement\utils.py", line 36, in get_user_permissions
    cursor.execute("""
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\PythonProjects\ERPCURSOR\Himalytix\erp\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: operator does not exist: boolean = integer
LINE 9:                     AND ur.is_active = 1
                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

